### ISSUE TITLE
using PDB/a3m as input files - SpeedPPI

### ISSUE THREAD

**Issue by soundharramsay** [patrickbryant1/SpeedPPI#11]
Can I use a PDB or a3m file as input for the SpeedPPI pipeline?  If yes, how to parse multiple PDB files as input as that of a FASTA seq. ( I wish to analyze 3 PDB versus 6 PDB files)

**Comment by patrickbryant1** [comment]
Hi, 

You have to input the sequences of these PDB/a3m files. There is no parser for the files directly. If you have a3m files, you do not have to build the MSAs, but the sequences are present in the first (second) row of the a3m files. I suggest you read up on what these files contain since there seems to be some confusion here. 

Best,

Patrick
