### ISSUE TITLE
Interpreting results

### ISSUE THREAD

**Issue by mcatto** [patrickbryant1/SpeedPPI#5]
Hi,

I have run SpeedPPI on some downloaded fasta files, but would like to know how to interpret the results. So far the pdockq is very low for the ones I have tried. One pairing has known interactions from molecular testing, but that does not seem to be the case from the _in silico_ results below.

ID,num_contacts,avg_if_plddt,pdockq
P17917-P53034,26,82.27374329869014,0.1136680691779636

I also used some examples from the dev folder, but am confused as to how to interpret the results (below). How can I find out if my run lines up with the examples?

ID,num_contacts,avg_if_plddt,pdockq
O15466-Q24JP5,241,69.97306386283624,0.5067867250038623

Are there parameters that could be changed to reflect conditions used in the molecular tests? Or is the low pdockq not an issue if the interactions are known from molecular testing, such that I can proceed to downstream analysis and visualization with the resulting .pdb files?

Thanks,
Michael

**Comment by patrickbryant1** [comment]
Hi,

We can't take responsibility for any interpretations of results, this will be up to the user. 

There are many issues with the field of PPIs related to different experimental technologies. To provide an intuition, you can read more about it here: https://www.nature.com/articles/s41594-022-00910-8

Notice that Y2H, mass spectrometry and structure determination find completely different interactions (Fig 1b). The question here is what technology is to be trusted and why. Any technology other than structure determination will also measure indirect interactions, but why these do not find all determined structures we can't answer. 

What we can say is that for structures that do not contain too much disorder, the pDockQ score is highly accurate across all of PDB vs known negative interactions (https://www.nature.com/articles/s41467-022-28865-w, fig 5). 

For other cases and technologies we can't really argue since it is not known what technology is the most accurate/to prefer.

Hope this helps!

**Comment by mcatto** [comment]
Thanks for the information! That makes sense about comparing across technologies.
