### ISSUE TITLE
scripts might benefit from a first line specifying the bash shell

### ISSUE THREAD

**Issue by GaryAitken** [patrickbryant1/SpeedPPI#7]
The test instructions specify running the scripts using something like:
```
bash create_ppi_some_vs_some.sh ...
```
This works fine, but if one makes the script executable and tries to run it using something like
```
./create_ppi_some_vs_some.sh ...
```
it fails with an error complaining about a bad for loop variable in step 3 in the code
```
for (( c=1; c<=$NUM_PREDS; c++ ))
```
The problem is because no shell is specified as the first line of the script, so /usr/bin/sh is used instead of /usr/bin/bash (or wherever the default sh script is).
Unless it causes some other cross-platform problems, it would be helpful if the scripts started with the line
```
#!/usr/bin/bash
```
Or at least mention in the README that because there is no shell explicitly set on the first line of the scripts, the bash command must be used to run the script.
(I encountered this when I started using the command
```
"nohup ./create_ppi_some_vs_some.sh ..."
```
instead of
```
"bash ./create_ppi_some_vs_some.sh ..."
```
because my terminal kept dropping and the process was terminated prematurely.)
Dumb mistake; I just assumed any .sh script would have the required shell specified.

**Comment by patrickbryant1** [comment]
Hi, the reason no shebang is specified is because different linux systems uses different paths. The same is true for running this on a cluster vs locally where the usr path may not always be accessible during the run depending on permissions. The safe option is therefore to have "bash" and if this is not modified, no error should be raised.

As you point out, it seems that this error arises because you modified the runscript or assumed certain paths.
